// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
)

const insertTodo = `-- name: InsertTodo :exec
INSERT INTO todos (description, done)
VALUES (?, ?)
RETURNING id, description, done, created_at
`

type InsertTodoParams struct {
	Description string
	Done        bool
}

func (q *Queries) InsertTodo(ctx context.Context, arg InsertTodoParams) error {
	_, err := q.db.ExecContext(ctx, insertTodo, arg.Description, arg.Done)
	return err
}

const listTodos = `-- name: ListTodos :many
SELECT id, description, done, created_at
FROM todos
WHERE done = false
ORDER BY id
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTodoDone = `-- name: MarkTodoDone :exec
UPDATE todos SET done = true WHERE id = ?
`

func (q *Queries) MarkTodoDone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markTodoDone, id)
	return err
}
